### ISSUE TITLE
[bug] can not start backend

### ISSUE THREAD

**Issue by yangjian102621** [filecoin-project/filecoin-network-stats#25]
well, i ran the command 

```
source .env && node ./dist/src/main.js
```
and i get the error:

```
{"err":{"message":"Invalid protocol: 127.0.0.1:","stack":"Error: Invalid protocol: 127.0.0.1:\n    at Request.init (/home/yangjian/workspace/ipfs/filecoin/filecoin-network-stats/backend/node_modules/request/request.js:458:31)\n
```
My `.env` file is 

```
export DB_URL=postgresql://filecoin:123456@localhost:5432
export FULL_NODE_URL=http://127.0.0.1:3453
export IS_MASTER=true
export PEER_INFO_FILE=./peerId.json
export HEARTBEAT_PORT=8090
export API_PORT=8081
export LOG_LEVEL=info
```

**Comment by mslipper** [comment]
Hi there,

Are you on the latest master branch?

**Comment by yangjian102621** [comment]
Yep, l pull the code before run the project, it is  the latest commit.

![image](https://user-images.githubusercontent.com/4746061/54729035-17fe7e00-4bbc-11e9-8591-914e5dac8d2d.png)

**Comment by mslipper** [comment]
I am unable to reproduce this locally - can you please place `console.log(this.url)` `callAPIStream` on line 34 and tell me the output?

**Comment by yangjian102621** [comment]
Well, there are two file contains `callAPIStream` method, i guess you mean the `HTTPClinent.js` file.

i placed the code  `console.log("url: " + this.url)`

![image](https://user-images.githubusercontent.com/4746061/54737408-c3bec280-4bea-11e9-8f3c-29c36baa66af.png)

Here is the output:

![image](https://user-images.githubusercontent.com/4746061/54737378-9f62e600-4bea-11e9-8251-80defcffa2e6.png)

My filecoin daemon is runing, and the api service is up.

![image](https://user-images.githubusercontent.com/4746061/54737463-0ed8d580-4beb-11e9-859c-940a25bfe9bd.png)

**Comment by mslipper** [comment]
How about dependencies - have you tried running `npm install` to make sure dependencies are up-to-date? Also, please set `LOG_LEVEL` to `silly` and paste the entire log here.

**Comment by yangjian102621** [comment]
Yep, in fact i ran `npm install` every time i had pull the code at once.

Here is my output in console.

```bash
yangjian@yangjian-desktop:/ipfs/filecoin/filecoin-network-stats/backend$ npm install

> filecoin-network-stats-backend@0.0.0 postinstall /home/yangjian/workspace/ipfs/filecoin/filecoin-network-stats/backend
> ./build/stub-debug.sh

find: ‘./node_modules/libp2p-floodsub/node_modules/debug’: No such file or directory
find: ‘./node_modules/multistream-select/node_modules/debug’: No such file or directory
find: ‘./node_modules/libp2p-switch/node_modules/debug’: No such file or directory
find: ‘./node_modules/libp2p-tcp/node_modules/debug’: No such file or directory
find: ‘./node_modules/libp2p-connection-manager/node_modules/debug’: No such file or directory
find: ‘./node_modules/libp2p/node_modules/debug’: No such file or directory
find: ‘./node_modules/libp2p-secio/node_modules/debug’: No such file or directory
find: ‘./node_modules/libp2p-mplex/node_modules/debug’: No such file or directory
find: ‘./node_modules/libp2p-circuit/node_modules/debug’: No such file or directory
find: ‘./node_modules/debug’: No such file or directory
find: ‘./node_modules/libp2p-floodsub/node_modules/debug_old’: No such file or directory
find: ‘./node_modules/debug_old’: No such file or directory
find: ‘./node_modules/multistream-select/node_modules/debug_old’: No such file or directory
find: ‘./node_modules/libp2p-switch/node_modules/debug_old’: No such file or directory
find: ‘./node_modules/libp2p-tcp/node_modules/debug_old’: No such file or directory
find: ‘./node_modules/libp2p-connection-manager/node_modules/debug_old’: No such file or directory
find: ‘./node_modules/libp2p/node_modules/debug_old’: No such file or directory
find: ‘./node_modules/libp2p-secio/node_modules/debug_old’: No such file or directory
find: ‘./node_modules/libp2p-mplex/node_modules/debug_old’: No such file or directory
find: ‘./node_modules/libp2p-circuit/node_modules/debug_old’: No such file or directory
npm WARN filecoin-network-stats-backend@0.0.0 No description
npm WARN filecoin-network-stats-backend@0.0.0 No repository field.

updated 10 packages and audited 5315 packages in 6.597s
found 0 vulnerabilities

yangjian@yangjian-desktop:/ipfs/filecoin/filecoin-network-stats/backend$ source .env && node dist/src/main.js
Heap dump written to: heapdump-19853219.889850.heapsnapshot
{"message":"started heartbeat server","level":"info","label":"HeartbeatServer","timestamp":"2019-03-21T07:38:08.828Z"}
{"path":"/sync/","method":"GET","level":"info","message":"mounted route","label":"APIServer","timestamp":"2019-03-21T07:38:08.832Z"}
{"path":"/miners/csv","method":"GET","level":"info","message":"mounted route","label":"APIServer","timestamp":"2019-03-21T07:38:08.833Z"}
{"path":"/stats/storage/historicalMinerCounts/:duration((all|24h|1w|1m|1y))","method":"GET","level":"info","message":"mounted route","label":"APIServer","timestamp":"2019-03-21T07:38:08.833Z"}
{"path":"/stats/storage/historicalStoragePrice/:duration((all|24h|1w|1m|1y))","method":"GET","level":"info","message":"mounted route","label":"APIServer","timestamp":"2019-03-21T07:38:08.833Z"}
{"path":"/stats/storage/historicalCollateral/:duration((all|24h|1w|1m|1y))","method":"GET","level":"info","message":"mounted route","label":"APIServer","timestamp":"2019-03-21T07:38:08.833Z"}
{"path":"/stats/storage/historicalCollateralPerGB/:duration((all|24h|1w|1m|1y))","method":"GET","level":"info","message":"mounted route","label":"APIServer","timestamp":"2019-03-21T07:38:08.833Z"}
{"path":"/stats/storage/historicalStorageAmount/:duration((all|24h|1w|1m|1y))","method":"GET","level":"info","message":"mounted route","label":"APIServer","timestamp":"2019-03-21T07:38:08.833Z"}
{"path":"/stats/storage/historicalUtilization/:duration((all|24h|1w|1m|1y))","method":"GET","level":"info","message":"mounted route","label":"APIServer","timestamp":"2019-03-21T07:38:08.833Z"}
{"path":"/stats/token/historicalBlockRewards/:duration((all|24h|1w|1m|1y))","method":"GET","level":"info","message":"mounted route","label":"APIServer","timestamp":"2019-03-21T07:38:08.833Z"}
{"path":"/stats/token/historicalCoinsInCirculation/:duration((all|24h|1w|1m|1y))","method":"GET","level":"info","message":"mounted route","label":"APIServer","timestamp":"2019-03-21T07:38:08.834Z"}
{"path":"/stats/market/historicalTokenVolume/:duration((all|24h|1w|1m|1y))","method":"GET","level":"info","message":"mounted route","label":"APIServer","timestamp":"2019-03-21T07:38:08.834Z"}
{"port":"8081","level":"info","message":"API server started","label":"APIServer","timestamp":"2019-03-21T07:38:08.834Z"}
{"message":"waiting for chainsaw before materializing stats","level":"info","label":"MaterializationService","timestamp":"2019-03-21T07:38:08.835Z"}
url: http://127.0.0.1:3453
{"err":{"message":"Invalid protocol: 127.0.0.1:","stack":"Error: Invalid protocol: 127.0.0.1:\n    at Request.init (/home/yangjian/workspace/ipfs/filecoin/filecoin-network-stats/backend/node_modules/request/request.js:458:31)\n    at new Request (/home/yangjian/workspace/ipfs/filecoin/filecoin-network-stats/backend/node_modules/request/request.js:127:8)\n    at request (/home/yangjian/workspace/ipfs/filecoin/filecoin-network-stats/backend/node_modules/request/index.js:53:10)\n    at Function.post (/home/yangjian/workspace/ipfs/filecoin/filecoin-network-stats/backend/node_modules/request/index.js:61:12)\n    at HTTPClient.callAPIStream (/home/yangjian/workspace/ipfs/filecoin/filecoin-network-stats/backend/dist/src/client/HTTPClient.js:46:31)\n    at ChainClientImpl.callAPIStream (/home/yangjian/workspace/ipfs/filecoin/filecoin-network-stats/backend/dist/src/client/HTTPClient.js:86:93)\n    at Promise (/home/yangjian/workspace/ipfs/filecoin/filecoin-network-stats/backend/dist/src/client/ChainClient.js:24:57)\n    at new Promise (<anonymous>)\n    at ChainClientImpl.<anonymous> (/home/yangjian/workspace/ipfs/filecoin/filecoin-network-stats/backend/dist/src/client/ChainClient.js:24:19)\n    at Generator.next (<anonymous>)"},"level":"error","message":"caught error during chainsaw run","label":"Chainsaw","timestamp":"2019-03-21T07:38:08.853Z"}
```
I suspect is it cause by my `.env` configuration incorrectly.

Thanks.

**Comment by yangjian102621** [comment]
Additional information: 

![image](https://user-images.githubusercontent.com/4746061/54739743-27012280-4bf4-11e9-9e01-0d3a996ac0ba.png)

**Comment by mslipper** [comment]
Did you get it wokring @yangjian102621 ?

**Comment by yangjian102621** [comment]
@mslipper 
Yep, what cause the problem is i had set the ENV variable `http_proxy=127.0.0.1:7777` in my `~/.bashrc` 

I commented the env variable and it worked.

Thanks.

But i had get another problem, when visit the page `http://llocalhost:8082:/storage/mining`, 
the page is stuck, click no response, also can not close the page, and i have to close my browser.
