### ISSUE TITLE
db-migrate failed on backend

### ISSUE THREAD

**Issue by urugang** [filecoin-project/filecoin-network-stats#32]
- db-migrate up  failed
```
$ DATABASE_URL=postgres://postgres:xxx@1@localhost:5432/filecoin-network-stats db-migrate   up

received data: CREATE INDEX block_height_idx ON blocks USING btree(height);
[INFO] Processed migration 20190606073105-add-block-height-index
[ERROR] AssertionError [ERR_ASSERTION]: ifError got unwanted exception: ENOENT: no such file or directory, open '/home/filecoin/codes/filecoin-network-stats/backend/migrations/sqls/20190608002923-update-trigger-param-type-up.sql'
    at /home/filecoin/codes/filecoin-network-stats/backend/node_modules/db-migrate/lib/commands/on-complete.js:15:14
    at tryCatcher (/home/filecoin/codes/filecoin-network-stats/backend/node_modules/bluebird/js/release/util.js:16:23)
    at Promise.successAdapter (/home/filecoin/codes/filecoin-network-stats/backend/node_modules/bluebird/js/release/nodeify.js:22:30)
    at Promise._settlePromise (/home/filecoin/codes/filecoin-network-stats/backend/node_modules/bluebird/js/release/promise.js:566:21)
    at Promise._settlePromiseCtx (/home/filecoin/codes/filecoin-network-stats/backend/node_modules/bluebird/js/release/promise.js:606:10)
    at _drainQueueStep (/home/filecoin/codes/filecoin-network-stats/backend/node_modules/bluebird/js/release/async.js:142:12)
    at _drainQueue (/home/filecoin/codes/filecoin-network-stats/backend/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/home/filecoin/codes/filecoin-network-stats/backend/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/filecoin/codes/filecoin-network-stats/backend/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)

```

**Comment by eshon** [comment]
Found the `20190608002923-update-trigger-param-type-up.sql` file in the commit history and re-installed it. It gets the db-migrate working although I'm not sure keeping it around is a goal.

**Comment by eshon** [comment]
Fixed via 1c6c43
